version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  order-service:
    build: .
    command: npm run start:dev
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=restaurant
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - .:/app
    ports:
      - '3001:3001'

  kitchen-service:
    build: .
    command: npm run start:dev kitchen
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=restaurant
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - .:/app

  notification-service:
    build: .
    command: npm run start:dev notification
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
